<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Ingot.Platform.Inspections.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Ingot.Platform.Application.Inspections" />
    <Using Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Ingot.Contracts\Ingot.Contracts.csproj" />
    <ProjectReference Include="..\Ingot.Platform.Application\Ingot.Platform.Application.csproj" />
  </ItemGroup>
</Project>
