version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /src/Ingot.Central.Web
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    groups:
      website:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /docs-site
    schedule:
      interval: weekly
    groups:
      docs-site:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
