version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /src/platform/Ingot.Platform.Web
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /apps/website
    schedule:
      interval: weekly
    groups:
      website:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /apps/docs-site
    schedule:
      interval: weekly
    groups:
      docs-site:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
