# 配置 Grafana 使用 Compose 网络中的 Prometheus 数据源。

apiVersion: 1

datasources:
  - name: Ingot Prometheus
    uid: ingot-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
