// 定义生产配置页面共享的资源元数据和显示标签。
export const productionResources = {
  context: {
    title: "生产切换", endpoint: "/api/v1/production-contexts", key: "contextId",
    description: "为设备选择接下来生产的产品、工艺规范和已装工装，保存后对新运行生效。",
    drawerDescription: "按顺序确认设备、产品、工艺规范和工装；保存后只影响新开始的生产运行。",
    columns: [["equipmentId", "设备"], ["productCode", "产品"], ["processSpecificationId", "工艺规范"], ["toolingInstallationId", "当前工装"], ["externalBatchRef", "生产批次"], ["validFrom", "生效时间"], ["validTo", "结束时间"]],
    template: { equipmentId: "", productFamilyCode: "", productCode: "", processSpecificationId: "", processSpecificationVersion: 1, toolingInstallationId: "", source: "manual", externalOrderRef: "", externalBatchRef: "", materialLotRef: "", materialSpecification: "", maintenanceStatus: "", calibrationStatus: "", calibrationRef: "", calibrationValidUntil: "" },
    createLabel: "配置下一批生产",
    requiredFields: ["equipmentId", "productFamilyCode", "productCode", "processSpecificationId", "toolingInstallationId"],
    prepare: value => ({
      ...value,
      validFrom: new Date().toISOString(),
      commandId: crypto.randomUUID(),
      calibrationValidUntil: value.calibrationValidUntil
        ? new Date(value.calibrationValidUntil).toISOString()
        : null,
    }),
    lifecycle: { label: "结束", visible: value => !value.validTo, url: value => `/api/v1/production-contexts/${value.contextId}:close`, body: () => ({ at: new Date().toISOString() }) },
  },
  installation: {
    title: "工装装卸", endpoint: "/api/v1/tooling-installations", key: "installationId",
    description: "记录哪个工装组合版本在何时装入设备，供后续运行自动关联。",
    drawerDescription: "选择设备和已经建立的工装组合版本，装入后会进入该设备的有效工装记录。",
    columns: [["equipmentId", "设备"], ["toolingAssemblyId", "工装"], ["installedAt", "装入"], ["removedAt", "卸下"]],
    template: { equipmentId: "", assemblyRevisionId: "", source: "manual" },
    createLabel: "装入工装",
    requiredFields: ["equipmentId", "assemblyRevisionId"],
    referenceFields: ["equipmentId", "assemblyRevisionId"],
    prepare: value => ({ ...value, installedAt: new Date().toISOString(), commandId: crypto.randomUUID() }),
    lifecycle: { label: "卸下", visible: value => !value.removedAt, url: value => `/api/v1/tooling-installations/${value.installationId}:remove`, body: () => ({ at: new Date().toISOString() }) },
  },
  componentType: {
    title: "组件分类", endpoint: "/api/v1/tooling-component-types", key: "componentTypeCode",
    description: "定义可复用物理资产的业务分类。",
    columns: [["componentTypeCode", "代码"], ["name", "名称"], ["status", "状态"], ["attributes", "属性"]],
    template: { componentTypeCode: "", name: "", status: "active", attributes: {} },
    createLabel: "新增组件分类",
    requiredFields: ["componentTypeCode", "name"],
    statusOptions: [["active", "启用"], ["inactive", "停用"]],
    deleteUrl: value => `/api/v1/tooling-component-types/${encodeURIComponent(value.componentTypeCode)}`,
  },
  component: {
    title: "组件资产", endpoint: "/api/v1/tooling-components", key: "componentId",
    description: "每条记录代表一件具有独立资产编号和序列号、可更换并需要追溯的物理组件。",
    columns: [["componentId", "资产编号"], ["componentTypeCode", "分类"], ["serialNo", "序列号"], ["name", "名称"], ["status", "资产状态"]],
    template: { componentId: "", componentTypeCode: "", serialNo: "", name: "", status: "available", attributes: {} },
    createLabel: "登记组件资产",
    requiredFields: ["componentId", "componentTypeCode", "serialNo", "name"],
    referenceFields: ["componentTypeCode"],
    statusOptions: [["available", "合格可用"], ["maintenance", "维护中"], ["retired", "已退役"]],
    deleteUrl: value => `/api/v1/tooling-components/${encodeURIComponent(value.componentId)}`,
  },
  type: {
    title: "工装结构定义", endpoint: "/api/v1/tooling-types", key: "toolingTypeCode",
    description: "定义一类工装总成包含哪些装配位置，以及每个位置允许使用哪种组件资产。",
    columns: [["toolingTypeCode", "代码"], ["version", "版本"], ["name", "名称"], ["status", "状态"], ["roles", "装配位置"]],
    template: { toolingTypeCode: "", version: 1, name: "", status: "active", roles: [] },
    createLabel: "新建工装结构",
    requiredFields: ["toolingTypeCode", "name"],
    statusOptions: [["active", "启用"], ["inactive", "停用"]],
    deleteUrl: value => `/api/v1/tooling-types/${encodeURIComponent(value.toolingTypeCode)}/${value.version}`,
  },
  assembly: {
    title: "实际工装总成", endpoint: "/api/v1/tooling-assemblies", key: "toolingAssemblyId",
    description: "维护工装总成身份，并通过不可变配置版本记录每个装配位置实际使用的组件资产。",
    columns: [["toolingAssemblyId", "工装总成编号"], ["name", "名称"], ["toolingTypeCode", "工装结构"], ["status", "状态"]],
    template: { toolingAssemblyId: "", toolingTypeCode: "", name: "", status: "active" },
    createLabel: "新建工装",
    requiredFields: ["toolingAssemblyId", "toolingTypeCode", "name"],
    referenceFields: ["toolingTypeCode"],
    statusOptions: [["active", "启用"], ["inactive", "停用"]],
    deleteUrl: value => `/api/v1/tooling-assemblies/${encodeURIComponent(value.toolingAssemblyId)}`,
  },
};

export const productionFieldLabels = {
  equipmentId: "设备编号",
  productFamilyCode: "产品系列",
  productCode: "产品编号",
  processSpecificationId: "工艺规范编号",
  processSpecificationVersion: "工艺规范版本",
  toolingInstallationId: "工装装卸记录",
  source: "记录来源",
  materialLotRef: "物料批次",
  externalOrderRef: "外部工单",
  externalBatchRef: "生产批次",
  materialSpecification: "材料规格",
  maintenanceStatus: "维护状态",
  calibrationStatus: "校准状态",
  calibrationRef: "校准记录",
  calibrationValidUntil: "校准有效期",
  assemblyRevisionId: "工装组合版本",
  componentTypeCode: "组件类型代码",
  name: "名称",
  status: "状态",
  attributes: "扩展属性",
  componentId: "组件编号",
  serialNo: "序列号",
  toolingTypeCode: "工装类型代码",
  version: "版本",
  roles: "装配位置",
  toolingAssemblyId: "工装编号",
};

export const productionConditionLabels = {
  released: "允许生产",
  due: "即将到期",
  valid: "有效",
  expired: "已过期",
};
